#!/usr/bin/env python3
"""csv_to_hosts - turn a CSV device list into inventory/hosts.yml."""

from __future__ import annotations

import argparse
import csv
import re
import sys
from pathlib import Path


PLATFORM_ALIASES: dict[str, str] = {
    "ios": "cisco_ios",
    "cisco_ios": "cisco_ios",
    "ios-xe": "cisco_xe",
    "ios-xe_": "cisco_xe",
    "xe": "cisco_xe",
    "cisco_xe": "cisco_xe",
    "nxos": "cisco_nxos",
    "cisco_nxos": "cisco_nxos",
    "asa": "cisco_asa",
    "cisco_asa": "cisco_asa",
    "ios-xr": "cisco_xr",
    "xr": "cisco_xr",
    "cisco_xr": "cisco_xr",
}

REQUIRED_COLUMNS = ("name", "ip address", "device type")
HOST_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_.-]*$")
IPV4_RE = re.compile(
    r"^(25[0-5]|2[0-4]\d|[01]?\d?\d)"
    r"(\.(25[0-5]|2[0-4]\d|[01]?\d?\d)){3}$"
)
HOSTNAME_RE = re.compile(
    r"^(?=.{1,253}$)(?!-)[A-Za-z0-9-]{1,63}(\.[A-Za-z0-9-]{1,63})*\.?$"
)

HEADER = (
    "---\n"
    "# inventory/hosts.yml\n"
    "#\n"
    "# Auto-generated by scripts/csv_to_hosts.py from a CSV device list.\n"
    "# Do not edit by hand unless you also stop regenerating this file.\n"
    "#\n"
    "# device_platform tells the module which Netmiko driver family to use\n"
    "# as a base (it auto-adjusts for telnet).\n"
    "# Common values: cisco_ios, cisco_xe, cisco_nxos, cisco_asa, cisco_xr\n"
    "#\n"
    "# device_port is optional - omit it to use the protocol default\n"
    "# (22 for ssh, 23 for telnet). Set it explicitly if a device uses a\n"
    "# non-standard port.\n"
    "\n"
    "all:\n"
    "  children:\n"
    "    network_devices:\n"
    "      hosts:\n"
)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="csv_to_hosts",
        description=(
            "Convert a CSV device list (columns: name, ip address, "
            "device type) into an Ansible hosts.yml inventory file."
        ),
    )
    parser.add_argument("csv_file", type=Path, help="path to input CSV")
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("inventory/hosts.yml"),
        help="path to output hosts.yml (default: inventory/hosts.yml)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite output file if it already exists",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="print the rendered YAML to stdout instead of writing",
    )
    parser.add_argument(
        "--allow-unknown",
        action="store_true",
        help="pass through unrecognised device types verbatim (with a warning)",
    )
    return parser.parse_args(argv)


def looks_like_ip(value: str) -> bool:
    if not value or any(ch.isspace() for ch in value):
        return False
    if IPV4_RE.match(value):
        return True
    if ":" in value and all(c in "0123456789abcdefABCDEF:" for c in value):
        return True
    return False


def read_rows(csv_path: Path) -> list[dict[str, str]]:
    with csv_path.open("r", encoding="utf-8-sig", newline="") as fh:
        lines = [
            line for line in fh
            if line.strip() and not line.lstrip().startswith("#")
        ]
    if not lines:
        raise ValueError(
            f"{csv_path}: CSV is empty or contains only comments"
        )
    reader = csv.DictReader(lines)
    fieldnames = [h for h in (reader.fieldnames or []) if h is not None]
    if not fieldnames:
        raise ValueError(f"{csv_path}: CSV is missing a header row")
    headers_lower = [h.strip().lower() for h in fieldnames]
    missing = [c for c in REQUIRED_COLUMNS if c not in headers_lower]
    if missing:
        raise ValueError(
            f"{csv_path}: missing required column(s): {', '.join(missing)}"
        )
    rows: list[dict[str, str]] = []
    for raw in reader:
        cleaned: dict[str, str] = {}
        for key, value in raw.items():
            if key is None:
                continue
            cleaned[key.strip().lower()] = (
                value.strip() if isinstance(value, str) else ""
            )
        if not any(cleaned.get(c) for c in REQUIRED_COLUMNS):
            continue
        rows.append(cleaned)
    return rows


def validate_rows(
    rows: list[dict[str, str]], allow_unknown: bool
) -> list[tuple[str, str, str]]:
    seen: dict[str, int] = {}
    errors: list[str] = []
    valid: list[tuple[str, str, str]] = []
    for idx, row in enumerate(rows, start=2):
        name = row.get("name", "")
        ip = row.get("ip address", "")
        dtype = row.get("device type", "")

        if not name:
            errors.append(f"line {idx}: 'name' is empty")
            continue
        if not HOST_NAME_RE.match(name):
            errors.append(
                f"line {idx}: invalid 'name' {name!r} "
                "(use letters, digits, '_', '.', '-'; cannot start with digit)"
            )
            continue
        if name in seen:
            errors.append(
                f"line {idx}: duplicate 'name' {name!r} "
                f"(first seen on line {seen[name]})"
            )
            continue
        seen[name] = idx

        if not ip:
            errors.append(f"line {idx}: 'ip address' is empty")
            continue
        if any(ch.isspace() for ch in ip):
            errors.append(
                f"line {idx}: 'ip address' {ip!r} contains whitespace"
            )
            continue
        if not (
            IPV4_RE.match(ip)
            or ("." in ip and HOSTNAME_RE.match(ip))
        ):
            errors.append(
                f"line {idx}: 'ip address' {ip!r} is not a valid "
                "IPv4 address or FQDN (hostnames must contain a dot)"
            )
            continue

        if not dtype:
            errors.append(f"line {idx}: 'device type' is empty")
            continue
        platform = PLATFORM_ALIASES.get(dtype.lower())
        if platform is None:
            if allow_unknown:
                print(
                    f"warning: line {idx}: unknown device type {dtype!r} "
                    "passed through verbatim",
                    file=sys.stderr,
                )
                platform = dtype
            else:
                errors.append(
                    f"line {idx}: unknown device type {dtype!r} "
                    "(use --allow-unknown to pass through, "
                    "or use one of: "
                    + ", ".join(sorted(set(PLATFORM_ALIASES.values()))) + ")"
                )
                continue

        valid.append((name, ip, platform))

    if errors:
        for err in errors:
            print(f"error: {err}", file=sys.stderr)
        raise SystemExit(1)
    return valid


def render_yaml(hosts: list[tuple[str, str, str]]) -> str:
    parts = [HEADER]
    for name, ip, platform in hosts:
        parts.append(f"        {name}:\n")
        parts.append(f"          ansible_host: {ip}\n")
        parts.append(f"          device_platform: {platform}\n")
        parts.append("\n")
    return "".join(parts).rstrip() + "\n"


def write_output(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        print(
            f"error: {path} already exists; pass --force to overwrite",
            file=sys.stderr,
        )
        raise SystemExit(1)
    tmp = path.with_name(path.name + ".tmp")
    try:
        with tmp.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)
        tmp.replace(path)
    finally:
        if tmp.exists():
            try:
                tmp.unlink()
            except OSError:
                pass


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if not args.csv_file.is_file():
        print(f"error: {args.csv_file}: not a file", file=sys.stderr)
        return 1
    try:
        rows = read_rows(args.csv_file)
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    valid = validate_rows(rows, allow_unknown=args.allow_unknown)
    rendered = render_yaml(valid)
    if args.dry_run:
        sys.stdout.write(rendered)
        print(
            f"# {len(valid)} host(s) would be written to {args.output}",
            file=sys.stderr,
        )
        return 0
    write_output(args.output, rendered, force=args.force)
    print(f"wrote {len(valid)} host(s) to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
